CXX = g++
CXXFLAGS = -Wall -std=c++17
SRC_DIR = src
OBJ_DIR = obj
BIN = chip8.exe

SRCS = $(wildcard $(SRC_DIR)/*.cpp) $(SRC_DIR)/tinyfiledialogs.c
OBJS = $(patsubst $(SRC_DIR)/%, $(OBJ_DIR)/%, $(SRCS:.cpp=.o))
OBJS := $(OBJS:.c=.o)

LIBS = -lSDL2 -lole32 -luuid -lcomdlg32

$(BIN): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LIBS)

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ_DIR)/*.o $(BIN)
